### ISSUE TITLE
libcache doubt

### ISSUE THREAD

**Issue by subhajit-cdot** [vel21ripn/nDPI#113]
Regarding libcache usage, did you measure the performance with your latest implementation? I can find libcache usage in ndpi dev branch, can you please brief what kind of optimization you achieve by using libcache implementation? 
I have another doubt, can you please tell why we take 1024 in case of ndpi_lru_cache_init for stun, mining, ookla etc. ? I suppose this cache is used for correlating multiple connection or packets of tls or ookla for protocol detection?

**Comment by vel21ripn** [comment]
I tried to reduce the amount of memory required for the library and make it reentrant.
So far, I do not see any point in further optimizing the library, since it is practically not used.

ndpi_lru_cache is used to quickly retrieve data that was received earlier in the current connection or in other similar connections. I don't know where the number 1024 came from.
ndpi_lru_cache is used more actively, but its effectiveness is extremely low. We need to think about how to improve the efficiency of using ndpi_lru_cache.
I will tackle this after I finish optimizing ahocorasick.

**Comment by subhajit-cdot** [comment]
Yes I was confused because 1024 is hard coded and used for cache initialization. In my understanding the cache for different protocol like stun,tls are initialized once and stored in ndpi_struct for eg in stun protocol it's called in ndpi_int_stun_add_connection(). The cache keeps the guessed protocol corresponding flows key generated using get_stun_lru_key(). Here my doubt is if there are 1024 different concurrent stun connections, will they ever match? Because the key(src ip, src port) will be different for all, so how the cache is useful for other similar connections?

**Comment by vel21ripn** [comment]
I think that first you need to collect a sufficient amount of traffic of each type and analyze the effectiveness of ndpi_lru_cache on it.
It takes a long time to test 150Gb of traffic every time (25 minutes).
I have only 16 GB of RAM on my test machine and even ssd/sata does not help. 100 MB/s is the limit for reading .pcap files

For each protocol, you will need to look for its own solution, including the refusal to use ndpi_lru_cache.

The topic with ndpi_lru_cache appeared due to a bug (https://github.com/ntop/nDPI/pull/1204)

**Comment by subhajit-cdot** [comment]
Yes I got your point. I have seen ntop#1204 and your findings are very significant. I wanted to clarify that ndpi_lru_cache can be used for different connection only if a source requests to different server using same protocol because I can see the cache key is generated using src addr and src port only ( atleast in case of stun protocol).
