### ISSUE TITLE
How to understand the --clevel and --inprogress parameters

### ISSUE THREAD

**Issue by someonebw** [vel21ripn/nDPI#135]
hi，vel21ripn
I noticed that your newly added parameter "confidence level"

//
Example of disabling several protocols:

iptables -A FORWARD -m ndpi --inprogress dns,tls -j ACCEPT
iptables -A FORWARD -m ndpi --clevel dpi --proto dns,tls -j DROP
iptables -A FORWARD -m ndpi --unknown -j ACCEPT

How to understand the --clevel and --inprogress parameters
Is it when you use --clevel
The --inprogress parameter must be configured

Clevel's match argument is
1 - port, 2 - ip, 3 - ip+port, 4 - dpi cache, 5 - dpi 

//
My understanding is
Rule1: clevel-level matches only for DNS and TLS protocols（Other agreements are not affected by this）

Rule2：
The matching process is up to dPI.
Is the match（match 5 times？？）
port -----》ip -----》ip+port -----》dpi cache  -----》dpi 

if myrule is
//iptables -A FORWARD -m ndpi --clevel ip --proto dns,tls -j DROP
//Is the match ip and port？？（match 2 times？？）
port -----》ip
Does it just match the ip, and the following 3 items will not match?

Can you give an example of a scenario that requires these two parameters?

**Comment by vel21ripn** [comment]
Some application protocols can only be detected after a few data packets. 
The "--inprogress" option checks the status of protocol detection. 
It will be true until the listed protocols are excluded from the detection process or a protocol with DPI confidence is detected.
The "--inprogress" option is useful for the tcp protocol, since it takes 3 packets to establish a connection and the actual detection process only starts with the fourth packet. Until then, we cannot reliably determine the application protocol.
On the first packet, we get guessed protocols with a confidence level of "port", "ip-address", "user defined", and after checking the following packets, the protocol can be determined more accurately, which can be checked using the "--clevel" option.
For the "tls" protocol, we will receive complete data no earlier than after three data packets.

Thanks for the "-p tcp -j REJECT" example. This is a special case which may need to be considered separately.

**Comment by someonebw** [comment]
hi,vel21ripn
Thank you for your answer.：）

I can see the relationship between these two parameters.

Only when I encounter appropriate application scenarios can I deeply understand the essence of using these two parameters together

Only the application scenarios and the configuration of related rules sample, I still need further experiments to understand them thoroughly.



"-p tcp -j REJECT" example
The original intention is to let the client in the fastest time, the response, rather than waiting for timeout;
So, use REJECT 。in tcp ，REJECT better then DROP。
：）
