### ISSUE TITLE
Why is kernel patch required?

### ISSUE THREAD

**Issue by halvors** [vel21ripn/nDPI#55]
It's not for https://github.com/betolj/ndpi-netfilter/ version?...

**Comment by vel21ripn** [comment]
Now patch is required if you want to simultaneously work ndpi-netfilter and connlabel.

The problem is simple - we need to track the deletion of data from conntack.
There are three options: kernel patch, interception nf_ct_destroy () and interception nf_conntrack_register_notifier ().
nf_conntrack_register_notifier can register only one handler, which is used by the kernel itself.
In https://github.com/ewildgoose/ndpi-netfilter, nf_conntrack_register_notifier () was replaced with a patch, but I could not get a stable long-term operation of this option (traffic 300-400 Mbit/s for 4-6 days led to the crash of the kernel)
The kernel patch is the safest way to solve this problem.
In my ndpi-netfilter, two options are offered: with a patch or with an interception nf_ct_destroy ().

**Comment by halvors** [comment]
@vel21ripn Thanks for explaining. I've experienced kernel crashes on older implementations of ndpi-netfilter, like the one from wildegoose.

How do i use nf_ct_destroy () instad of a patched kernel?
What is the disadvantages of using that option?

Maybe there should be done effort in upstream kernel to provide the needed hooks in the kernel itself?

**Comment by vel21ripn** [comment]
> How do i use nf_ct_destroy () instad of a patched kernel?

Don't use patch for kernel :) 
In the ndpi-netfilter module there is a conditional compilation depending on the presence of a kernel patch.

> What is the disadvantages of using that option?

It's a hack. 

> Maybe there should be done effort in upstream kernel to provide the needed hooks in the kernel itself?

I tried to do it a few years ago, but the patch was not accepted with the wording "too radical."

**Comment by halvors** [comment]
@vel21ripn Is there a pull request you could link me?

**Comment by vel21ripn** [comment]
https://patchwork.ozlabs.org/patch/284021/
Pull-request to the official Linux kernel is a very long process. I see no reason to spend time on it.
This is a very specific patch that the rest do not need.
