### ISSUE TITLE
"iptables -m ndpi .." rules cannot run in a DOCKER Container .

### ISSUE THREAD

**Issue by usama2490** [vel21ripn/nDPI#66]
Hi, 
    I have built this Dockerfile https://gist.github.com/elico/1c92fcee150ce3a02cb2c122588fda15  in order to run ndpi integrated with net-filter in a Docker container. Docker image is successfully built and i have run the container based on this image. The issue is when i login to this container and then trying to implement a rule as "sudo iptables -m ndpi --help", it gave an exception "iptables v1.6.0: Couldn't load match `ndpi':No such file or directory".  

Kindly tell as i am unable to implement any kind of blocking rule in a container ? 
Regards

**Comment by elico** [comment]
@usama2490 This specific container was designed only to compile the module.
I am not sure you understand how containers works since you cannot do what you want in a container..
Or at-least it's the wrong way to touch another OS kernel if at all.

A Docker container uses the hosting kernel and do not load any kernel module by itself.
In theory it is possible to load the kernel modules from within a Docker container but you shouldn't and it's possible that you will cause some host kernel issues if not panic doing so.

If you need a customized kernel you need a dedicated machine(VM or physical).

Just to make clear what this container is for: to pre-compile the module without compromising the integrity of the production machine.

**Comment by usama2490** [comment]
Thanks for your reply, i completely understand what you are saying. let me explain what i want to do, i have tried ndpi & netfilter in a VM as per the requirements given in this link https://github.com/betolj/ndpi-netfilter and it worked perfectly fine for me. But now i have been asked to do the same thing in a Docker Container and for that purpose i have to redirect the host traffic into a Docker Container and compile this whole module within that Container and try to implement those blocking rules in a Container.
I have done this on Virtual machine but now i have to do this in a container that Host traffic should first reroute or must be forwarded to the Docker container and within that container ndpi & netfilter should be running and i should be able to implement those rules on Host traffic in a container and then traffic should take path from container (where ndpi firewall is running) to the Host and external world.

**Comment by vel21ripn** [comment]
The "flow_info" branch should work on unmodified kernels.
My version of xt_ndpi supports the network namespaces (used in docker and lxc).

**Comment by elico** [comment]
@usama2490 I am not sure you understand yet..
The Docker container is using and only using the Docker **Host**  kernel.
First try to learn about iptables and Docker containers and then decide if it's the right thing to try to change iptables and use a complex module such as nDPI on a Docker **Host**.
- <https://docs.docker.com/network/iptables/>
