### ISSUE TITLE
debian 8   kernel 4.19.53

### ISSUE THREAD

**Issue by WISSAM-CRS** [vel21ripn/nDPI#72]
hello,

i have this error after running the make command

root@office-test1:~/nDPI/ndpi-netfilter# make
make -C ipt
make[1]: Entering directory '/root/nDPI/ndpi-netfilter/ipt'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/nDPI/ndpi-netfilter/ipt'
make -C src
make[1]: Entering directory '/root/nDPI/ndpi-netfilter/src'
grep: /lib/modules/4.19.53/source/include/linux/skbuff.h: No such file or directory
$xt_ndpi-y is [main.o ndpi_strcol.o ndpi_proc_parsers.o ndpi_proc_generic.o ndpi_proc_info.o  ndpi_proc_flow.o ndpi_proc_hostdef.o ndpi_proc_ipdef.o ../libre/regexp.o ../../src/lib/third_party/src/node.o ../../src/lib/third_party/src/ahocorasick.o ../../src/lib/third_party/src/libcache.o ../../src/lib/third_party/src/ndpi_patricia.o ../../src/lib/third_party/src/ht_hash.o ../../src/lib/third_party/src/btlib.o ../../src/lib/ndpi_main.o ../../src/lib/protocols/*.o] -I/../../src/include -I/../../src/lib -I/../libre -I/../../src/lib/third_party/include  -DHAVE_CONFIG_H -DNDPI_LIB_COMPILATION -DOPENDPI_NETFILTER_MODULE -g -femit-struct-debug-detailed=any
\
make  -C /lib/modules/4.19.53/build M=$PWD modules -w;
make[2]: Entering directory '/root/nDPI/ndpi-netfilter/src'
make[2]: *** /lib/modules/4.19.53/build: No such file or directory.  Stop.
make[2]: Leaving directory '/root/nDPI/ndpi-netfilter/src'
Makefile:37: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: Leaving directory '/root/nDPI/ndpi-netfilter/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

can you help in english please

**Comment by vel21ripn** [comment]
You cannot build a module without kernel sources.
Each Linux distribution has documentation for building the kernel.
It lists the packages needed to build the kernel and modules.

**Comment by WISSAM-CRS** [comment]
Can you give us details how to build kermel for debian jessie 8 ?

**Comment by WISSAM-CRS** [comment]
> It lists the packages needed to build the kernel and modules.

Can you give us more details in the step we should follow to arrive to our target deployment ndpi-netfilter.
our target is to use this to redirect Netfliter traffic to a specific router interface, is it the ideal solution for it or what do you propose if not!

thank you for your help

**Comment by vel21ripn** [comment]
> Can you give us more details in the step we should follow to arrive to our target deployment ndpi-netfilter.

I am using linux Slackware. The problems of building kernel modules in other distributions do not interest me.

> our target is to use this to redirect Netfliter traffic to a specific router interface, is it the ideal solution for it or what do you propose if not!

There is a serious problem. Since traffic is identified by its contents, at the time of the connection establishment we have an "unknown" protocol. The decision to redirect traffic should be made at the time the first packet is received when the protocol is not yet defined. You cannot change the outbound interface after establishing a connection using SNAT.
Perhaps this problem can be solved this way: after detecting traffic with a specific protocol, we write the address, port and protocol (tcp / udp) in ipset (type hash:ip,port).
If a new connection is established with the address and port from ipset, then we redirect traffic through a specific interface.

**Comment by WISSAM-CRS** [comment]
If I pay for this solution , are interested to create this for us ? 
We will deploy this solution on our routers.
